// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp_Jqi6Aci-1kxKDu3DzmHaLv33O3fwA4',
    appId: '1:596112830230:web:f06da8c7a34ecef608ea37',
    messagingSenderId: '596112830230',
    projectId: 'campconnect-da0ea',
    authDomain: 'campconnect-da0ea.firebaseapp.com',
    storageBucket: 'campconnect-da0ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbHZG8E7MwSsDezA5ox1h7rXub4WSVJ7A',
    appId: '1:596112830230:android:fa3e3fa0ed98611f08ea37',
    messagingSenderId: '596112830230',
    projectId: 'campconnect-da0ea',
    storageBucket: 'campconnect-da0ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM6BKyCfil9GByNmoT7a32f76ufruLm8Y',
    appId: '1:596112830230:ios:655dabd758de320a08ea37',
    messagingSenderId: '596112830230',
    projectId: 'campconnect-da0ea',
    storageBucket: 'campconnect-da0ea.firebasestorage.app',
    iosBundleId: 'com.example.campConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM6BKyCfil9GByNmoT7a32f76ufruLm8Y',
    appId: '1:596112830230:ios:655dabd758de320a08ea37',
    messagingSenderId: '596112830230',
    projectId: 'campconnect-da0ea',
    storageBucket: 'campconnect-da0ea.firebasestorage.app',
    iosBundleId: 'com.example.campConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp_Jqi6Aci-1kxKDu3DzmHaLv33O3fwA4',
    appId: '1:596112830230:web:d27afda467a18f3208ea37',
    messagingSenderId: '596112830230',
    projectId: 'campconnect-da0ea',
    authDomain: 'campconnect-da0ea.firebaseapp.com',
    storageBucket: 'campconnect-da0ea.firebasestorage.app',
  );

}