final List<Map<String, dynamic>> dummyEvents = [
  {
    'title': 'Intro to Web Dev',
    'date': '2026-02-13',
    'startTime': '09:00',
    'endTime': '10:30',
    'location': 'Room 101',
    'description': 'Basics of HTML, CSS, and JavaScript.',
  },
  {
    'title': 'Design Club Meetup',
    'date': '2026-02-13',
    'startTime': '14:00',
    'endTime': '15:30',
    'location': 'Design Lab',
    'description': 'Meet the design club members.',
  },
  {
    'title': 'Cyber Security 101',
    'date': '2026-02-14',
    'startTime': '09:00',
    'endTime': '10:30',
    'location': 'Seminar Hall B',
    'description': 'Introduction to cyber security concepts.',
  },
  {
    'title': 'Photography Walk',
    'date': '2026-02-14',
    'startTime': '15:00',
    'endTime': '16:30',
    'location': 'Campus Grounds',
    'description': 'Hands-on photography practice.',
  },
  {
    'title': 'UI/UX Basics',
    'date': '2026-02-15',
    'startTime': '10:00',
    'endTime': '11:30',
    'location': 'Room 305',
    'description': 'Fundamentals of UI/UX design.',
  },
  {
    'title': 'Python for Beginners',
    'date': '2026-02-16',
    'startTime': '09:00',
    'endTime': '11:00',
    'location': 'Lab 2',
    'description': 'Learn Python from scratch.',
  },
  {
    'title': 'Alumni Interaction Session',
    'date': '2026-02-16',
    'startTime': '14:00',
    'endTime': '15:30',
    'location': 'Auditorium C',
    'description': 'Career guidance from alumni.',
  },
  {
    'title': 'Tech Talk: Flutter Basics',
    'date': '2026-02-17',
    'startTime': '10:00',
    'endTime': '11:30',
    'location': 'Auditorium A',
    'description': 'Introductory Flutter session.',
  },
  {
    'title': 'AI Club Orientation',
    'date': '2026-02-17',
    'startTime': '14:00',
    'endTime': '15:30',
    'location': 'Room 204',
    'description': 'Orientation for AI Club.',
  },
  {
    'title': 'Open Source Meetup',
    'date': '2026-02-18',
    'startTime': '10:00',
    'endTime': '11:30',
    'location': 'Innovation Hall',
    'description': 'Discuss open-source contributions.',
  },
  {
    'title': 'Hackathon Meetup',
    'date': '2026-02-18',
    'startTime': '15:00',
    'endTime': '16:30',
    'location': 'Innovation Lab',
    'description': 'Team up for upcoming hackathons.',
  },
  {
    'title': 'Startup Pitch Night',
    'date': '2026-02-19',
    'startTime': '18:00',
    'endTime': '20:00',
    'location': 'Main Auditorium',
    'description': 'Pitch startup ideas to mentors.',
  },
  {
    'title': 'Data Science Bootcamp',
    'date': '2026-02-20',
    'startTime': '09:00',
    'endTime': '12:00',
    'location': 'Lab 5',
    'description': 'Hands-on data science workshop.',
  },
  {
    'title': 'Competitive Coding Contest',
    'date': '2026-02-20',
    'startTime': '14:00',
    'endTime': '17:00',
    'location': 'Online',
    'description': 'Test your coding skills.',
  },
  {
    'title': 'Resume Review Session',
    'date': '2026-02-21',
    'startTime': '10:00',
    'endTime': '12:00',
    'location': 'Placement Cell',
    'description': 'Get your resume reviewed.',
  },
  {
    'title': 'Machine Learning Basics',
    'date': '2026-02-22',
    'startTime': '09:00',
    'endTime': '11:00',
    'location': 'Room 401',
    'description': 'Intro to machine learning.',
  },
  {
    'title': 'Cloud Computing Workshop',
    'date': '2026-02-22',
    'startTime': '14:00',
    'endTime': '16:00',
    'location': 'Seminar Hall A',
    'description': 'Learn AWS & cloud fundamentals.',
  },
  {
    'title': 'Annual Tech Fest',
    'date': '2026-02-23',
    'startTime': '09:00',
    'endTime': '18:00',
    'location': 'Campus Ground',
    'description': 'Flagship annual tech festival.',
  },
  {
    'title': 'Robotics Expo',
    'date': '2026-02-24',
    'startTime': '10:00',
    'endTime': '16:00',
    'location': 'Mechanical Block',
    'description': 'Showcase of robotics projects.',
  },
  {
    'title': 'Game Development Jam',
    'date': '2026-02-25',
    'startTime': '09:00',
    'endTime': '17:00',
    'location': 'Innovation Lab',
    'description': 'Build a game in 24 hours.',
  },
  {
    'title': 'Women in Tech Panel',
    'date': '2026-02-26',
    'startTime': '14:00',
    'endTime': '15:30',
    'location': 'Auditorium B',
    'description': 'Panel discussion with women leaders.',
  },
  {
    'title': 'Blockchain Fundamentals',
    'date': '2026-02-27',
    'startTime': '10:00',
    'endTime': '11:30',
    'location': 'Room 210',
    'description': 'Learn blockchain basics.',
  },
  {
    'title': 'Career Fair',
    'date': '2026-02-28',
    'startTime': '10:00',
    'endTime': '16:00',
    'location': 'Main Hall',
    'description': 'Meet recruiters and startups.',
  },
];
